version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder # Use the builder stage for development
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules # Anonymous volume for node_modules
    environment:
      - NODE_ENV=development
      - PORT=8080
    command: npm run start:dev
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 30s